Feature/analytics add feature functions
corca-ai/adcio-ios-sdk pull request #2
Opened 2023-10-27 09:20 UTC by snack655

## :pushpin: Type of PR
feature

## :recycle: Current situation
* Network 통신 함수 추가.
* 패키지 기본 entity 추가. (AdcioLogOption)
* 사용자가 사용할 함수 추가.

## :bulb: Proposed solution
* 28f858895be4670ce31082d1c338c820ab033497 : 전 Repository의 개발된 부분 가져오기.
  * 사용자 함수, APIManager, Entity 기본적인 구현은 모두 완료되어있었습니다.
* b114ccf0bef77d779c13004bf2bb1bb5e872b7cd : 전체 페키지들을 묶어서 부를 이름 설정.
  * Kakao SDK의 KakaoOpenSDK 참고하여 AdcioOpenSDK로 명명
  * 혹시 더 좋은 이름이 있다면 코맨트 부탁드립니다!
  * PR과 상관 없는 작업 내용 죄송합니다ㅠㅠ
* a9fa27180fc9220e31ed18bb2f3a89d5455afa79: APIManager가 400 대의 error를 감지하지 못하는 오류 수정 및 response debugPrint 작성.
  * 보기 힘든 중첩 if 로직을 탈출할 수 있는 좋은 로직은 언제든 환영입니다. ㅠㅠ
 
## 검증
Example 앱을 로컬에 개발하여 검증을 진행하였습니다.
https://drive.google.com/drive/folders/1P9oDaWnOlVA0dQ68rYAD5UiQ6hGCyPSP?usp=sharing
위 링크에서 Example 앱을 받을 수 있습니다.
### 성공
![image](https://github.com/corca-ai/adcio-ios-sdk/assets/80940200/bc9e9196-5878-41ee-ac12-0a9bdc4a8036)
### 실패
![image](https://github.com/corca-ai/adcio-ios-sdk/assets/80940200/c281e363-fa34-4187-a640-dc500b71c468)

## 다음 작업
* ImpressionDetector 개발.
  * 로컬의 test project에서 코드 테스트 예정.

2023-10-30 02:41 UTC, adbr-dev commented on Sources/AdcioAnalytics/AdcioAnalytics.swift
> +            sessionId: sessionId ?? "SAMPLE SESSION ID",
이거는 adcio core 배포되면 바꿀려고 저렇게 해두신거죠?
그러면 `// TODO:` , `// FIXME:` 로 주석 남겨주세요!

참고 블로그: https://ios-development.tistory.com/1361
참고 이미지:
![image](https://github.com/corca-ai/adcio-ios-sdk/assets/51875059/43c7a729-b0f2-4b52-bb71-9cc7f390ec7e)

2023-10-30 03:20 UTC, adbr-dev requested changes

2023-10-30 03:20 UTC, adbr-dev commented on Sources/AdcioAnalytics/Network/APIManager.swift
이부분이 많이 어지럽긴 한데 제가 이 부분을 막 수정했을 때
잘 작동 되는지?가 잘 모르겠어서 .. 이부분 자리에서 함께 고쳐도 될까요? @snack655

2023-10-30 03:23 UTC, snack655 commented on Sources/AdcioAnalytics/AdcioAnalytics.swift
> +            sessionId: sessionId ?? "SAMPLE SESSION ID",
아하 넵 수정하겠습니다!

2023-10-30 03:24 UTC, snack655 commented on Sources/AdcioAnalytics/Network/APIManager.swift
넵 좋습니다!

2023-10-30 03:26 UTC, snack655 commented on Sources/AdcioAnalytics/AdcioAnalytics.swift
> +            sessionId: sessionId ?? "SAMPLE SESSION ID",
이 부분 그냥 AdcioCore 적용해서 Commit 날려도 될까요??

2023-10-30 03:45 UTC, aahspringaa4 commented on Sources/AdcioAnalytics/Network/APIManager.swift
> +                            }
500+에러 생각하면 첫번쨰 if 문을 200...299 으로 하고 나머지는 else로 처리해도 될 것 같아요.

2023-11-02 02:31 UTC, adbr-dev approved these changes
나머지는 다 좋습니다! 우선 approve하고 baseUrl에 대한 답변 두분 다 생각하시고 통일성 맞춰주셨으면 합니다!

@snack655 @aahspringaa4

2023-11-02 02:58 UTC, snack655 commented on Sources/AdcioAnalytics/AdcioAnalytics.swift
> +private let BASE_URL = "https://receiver-dev.adcio.ai/"
android에서 작성하던 습관이 나왔었네요.. baseUrl로 네이밍 수정 및 receiver-dev -> receiver로 변경하여 commit 하였습니다.
https://github.com/corca-ai/adcio-ios-sdk/pull/2/commits/367610ad5bfb53f1478355ae4bacdabb32e6a20b

2023-11-02 05:43 UTC, merged