Feature/impl methodchannel
corca-ai/adcio-ios-sdk pull request #7
Opened 2023-11-06 09:04 UTC by aahspringaa4

Agent에서 product 클릭시 channel로 productId 받아오기 구현하였습니다!

AdcioAgent 선언 시 파라미터에 클로져를 생성하여 ProductId를 반환 받을 수 있습니다!

예제 코드 
```
AdcioAgent(
      onClickProduct: { productId in
          print("Product clicked with ID: \(productId)")
      }
  )
```

2023-11-06 09:14 UTC, adbr-dev requested changes

2023-11-06 09:14 UTC, adbr-dev commented on Sources/AdcioAgent/AdcioCoordinator.swift
> +public class AdcioCoordinator: NSObject, WKNavigationDelegate, WKScriptMessageHandler {
public class 여서 컨트롤을 클라이언트 개발자가 할 수 있게되는게.. 조금 걸려요..

2023-11-06 09:14 UTC, adbr-dev commented on Sources/AdcioAgent/AdcioAgent.swift
> +    public func makeCoordinator() -> AdcioCoordinator {
override 된 함수 라서 public func인데..
저걸 외부 개발자가 수정할 수 없게 제어관리 차원에서 봐주세요

2023-11-07 01:05 UTC, aahspringaa4 reviewed
AdcioAgent에서 자식 함수, Agent 함수(isStartPage, agentGoBack)만 public 으로 변경,
그 외 다른 함수들은 private로 변경하였습니다!

2023-11-07 01:17 UTC, adbr-dev approved these changes
굿! 고생하셨습니당 👏👏👏 internal init 쓰는거 우리 private class로 쓰일 곳에 잊지 않고 상황에 맞춰 다음번에도 미리 사용해주세요!!

2023-11-07 01:18 UTC, merged